// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlgsulvmyaueocznipap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ3N1bHZteWF1ZW9jem5pcGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTY5NjcsImV4cCI6MjA2NTgzMjk2N30.l8OAFX56SXMklZerN1QAxmtgR2ngnvOKzV14lGeAeUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);